version: '3.8'

services:
  app:
    container_name: go-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always
    volumes:
      - ./app:/usr/src/app

networks:
  default:
    driver: bridge